
services:
  web:
    image: node:18
    container_name: hello-node
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    command: >
      sh -c "npm install && node index.js"
